### PR TITLE
Fixes https://github.com/eclipse/deeplearning4j/issues/9393

### LINKED ISSUE #9393: INDArray.match(Number, Condition) not returning expected results.
**Expected behavior:**
`array.match(n, Conditions.equals())` should return a mask such that each entry `mask.get(i)` is `array[i] == n`

**Encountered behavior:**

the mask contains incorrect booleans for anything but `n=0`. 

#### Version Information

Please indicate relevant versions, including, if relevant:

* nd4j version beta 7. 
* Platform information (OS, etc): Windows 10 Enterprise

#### To reproduce: 

The following code will reproduce the error for `i > 0`:

        int[] assignments = {0,0,0,1,0,2,2};
        int[] indexes     = {0,1,2,3,4,5,7};

        INDArray asarray = Nd4j.createFromArray(assignments);
        INDArray idxarray = Nd4j.createFromArray(indexes);

        int i = 1; 
        INDArray mask = asarray.match(i, Conditions.equals());

- `i=1` results in the mask ` [ false, false, false, true, false, true, true]`
- `i=2` results in the mask ` [ false, false, false, false, false, false, false]`

There seem to be similar problems with `notEquals()` and `notEquals(someNumber)`. Everything is inverted or totally incorrect. 

#### Contributing

I would love to contribute, but might need guidance.

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Fixes conditional dispatch bug by allowing the setting of the number for the condition.
The user gets to benefit from an intuitive conditions api with minimal changes to the internals.
Fixes #9393 

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/And.java [hunk 1]
```diff
@@ -28,6 +28,11 @@ public And(Condition... conditions) {
         this.conditions = conditions;
     }
 
+    @Override
+    public void setValue(Number value) {
+
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/And.java]: A comment for why this is empty would be useful.

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/ConditionEquals.java [hunk 2]
```diff
@@ -28,6 +28,11 @@ public ConditionEquals(Condition... conditions) {
         this.conditions = conditions;
     }
 
+    @Override
+    public void setValue(Number value) {
+
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/ConditionEquals.java]: Again, a comment why this is empty would be useful.

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/EqualsCondition.java [hunk 3]
```diff
@@ -43,7 +43,7 @@ public EqualsCondition(Number value) {
      */
     @Override
     public int condtionNum() {
-        return 10;
+        return 0;
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/EqualsCondition.java:48]: Why is this 0 now?

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Not.java [hunk 4]
```diff
@@ -24,6 +24,11 @@
 
     private Condition opposite;
 
+    @Override
+    public void setValue(Number value) {
+
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Not.java]: Again, a comment why this is empty would be useful.

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Or.java [hunk 5]
```diff
@@ -28,6 +28,11 @@ public Or(Condition... conditions) {
         this.conditions = conditions;
     }
 
+    @Override
+    public void setValue(Number value) {
+
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Or.java]: Again, a comment why this is empty would be useful.

**Review by treo — CHANGES_REQUESTED** [review]

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/EqualsCondition.java (hunk 3 above)
Comment (agibsonccc) [reply nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/EqualsCondition.java:48]: @treo this was due to the conditions. See new javadoc: https://github.com/eclipse/deeplearning4j/blob/efbeccf3985d0cc1bfa0a012c16cae29e1075a76/nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/conditions/Condition.java#L36 here basically we could put equals (0) or absolute difference equals. I'm ok with either 0 or 10 here.

**Comment by agibsonccc** [comment]
@treo feedback factored in

**Review by treo — APPROVED** [review]
