### PR TITLE
#565 - JSON serialization for InputPreProcessor

### LINKED ISSUE #565: MultiLayerNeuralNetConfigurationTest - JsonMappingException
MultiLayerNeuralNetConfigurationTest (dl4j-core) unit test fails with JSON mapping exception.     
```
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: 
Can not construct instance of org.deeplearning4j.nn.conf.InputPreProcessor, 
problem: abstract types either need to be mapped to concrete types, have custom deserializer, 
or be instantiated with additional type information
 at [Source: {
  "hiddenLayerSizes" : null,
  "confs" : [ {
    "sparsity" : 0.0,
    "useAdaGrad" : true,
    "lr" : 0.10000000149011612,
    "corruptionLevel" : 0.30000001192092896,
    "numIterations" : 5,
    "momentum" : 0.5,
    "l2" : 0.0,
    "useRegularization" : false,
    "updater" : "ADAGRAD",
    "customLossFunction" : null,
    "momentumAfter" : null,
    "resetAdaGradIterations" : -1,
    "maxNumLineSearchIterations" : 5,
    "dropOut" : 0.0,
    "applySparsity" : false,
    "weightInit" : "VI",
    "optimizationAlgo" : "CONJUGATE_GRADIENT",
    "lossFunction" : "RECONSTRUCTION_CROSSENTROPY",
    "constrainGradientToUnitNorm" : false,
    "rho" : 0.0,
    "seed" : 1439534149300,
    "dist" : {
      "normal" : {
        "mean" : 1.0,
        "std" : 0.1
      }
    },
    "stepFunction" : null,
    "layer" : {
      "RBM" : {
        "activationFunction" : null,
        "weightInit" : null,
        "dist" : null,
        "dropOut" : 0.0,
        "updater" : null,
        "hiddenUnit" : null,
        "visibleUnit" : null,
        "k" : 0,
        "nin" : 0,
        "nout" : 0
      }
    },
    "variables" : [ ],
    "activationFunction" : "sigmoid",
    "useDropConnect" : false,
    "visibleUnit" : "BINARY",
    "hiddenUnit" : "BINARY",
    "k" : 0,
    "weightShape" : [ 0, 0 ],
    "timeSeriesLength" : 1,
    "kernelSize" : [ 2, 2 ],
    "stride" : [ 2, 2 ],
    "padding" : [ 0, 0 ],
    "batchSize" : 100,
    "minimize" : false,
    "l1" : 0.0,
    "rmsDecay" : 0.0,
    "miniBatch" : false,
    "convolutionType" : "VALID",
    "poolingType" : "MAX",
    "nin" : 0,
    "nout" : 0
  }, {
    "sparsity" : 0.0,
    "useAdaGrad" : true,
    "lr" : 0.10000000149011612,
    "corruptionLevel" : 0.30000001192092896,
    "numIterations" : 5,
    "momentum" : 0.5,
    "l2" : 0.0,
    "useRegularization" : false,
    "updater" : "ADAGRAD",
    "customLossFunction" : null,
    "momentumAfter" : null,
    "resetAdaGradIterations" : -1,
    "maxNumLineSearchIterations" : 5,
    "dropOut" : 0.0,
    "applySparsity" : false,
    "weightInit" : "VI",
    "optimizationAlgo" : "CONJUGATE_GRADIENT",
    "lossFunction" : "RECONSTRUCTION_CROSSENTROPY",
    "constrainGradientToUnitNorm" : false,
    "rho" : 0.0,
    "seed" : 1439534149300,
    "dist" : {
      "normal" : {
        "mean" : 1.0,
        "std" : 0.1
      }
    },
    "stepFunction" : null,
    "layer" : {
      "RBM" : {
        "activationFunction" : null,
        "weightInit" : null,
        "dist" : null,
        "dropOut" : 0.0,
        "updater" : null,
        "hiddenUnit" : null,
        "visibleUnit" : null,
        "k" : 0,
        "nin" : 0,
        "nout" : 0
      }
    },
    "variables" : [ ],
    "activationFunction" : "sigmoid",
    "useDropConnect" : false,
    "visibleUnit" : "BINARY",
    "hiddenUnit" : "BINARY",
    "k" : 0,
    "weightShape" : [ 0, 0 ],
    "timeSeriesLength" : 1,
    "kernelSize" : [ 2, 2 ],
    "stride" : [ 2, 2 ],
    "padding" : [ 0, 0 ],
    "batchSize" : 100,
    "minimize" : false,
    "l1" : 0.0,
    "rmsDecay" : 0.0,
    "miniBatch" : false,
    "convolutionType" : "VALID",
    "poolingType" : "MAX",
    "nin" : 0,
    "nout" : 0
  } ],
  "useDropConnect" : false,
  "useGaussNewtonVectorProductBackProp" : false,
  "pretrain" : true,
  "useRBMPropUpAsActivations" : false,
  "dampingFactor" : 100.0,
  "outputPostProcessors" : { },
  "inputPreProcessors" : {
    "1" : { }
  },
  "backward" : false,
  "backprop" : false
}; line: 137, column: 5] (through reference chain: org.deeplearning4j.nn.conf.MultiLayerConfiguration["inputPreProcessors"]->java.util.LinkedHashMap["1"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:857)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:333)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration.fromJson(MultiLayerConfiguration.java:132)
	at org.deeplearning4j.nn.conf.MultiLayerNeuralNetConfigurationTest.testJson(MultiLayerNeuralNetConfigurationTest.java:55)
```

### PR DESCRIPTION
**Pull request by EronWright**
Added Data annotation to the known input preprocessors, annotated the
constructors, and added the JsonSubTypes annotation to the interface.

With that, the preprocessors are handled much as other polymorphic conf
elements are.  Sample JSON output:

```
"inputPreProcessors" : {
    "0" : {
      "feedForwardToCnn" : {
        "inputWidth" : 28,
        "inputHeight" : 28,
        "numChannels" : 1
      }
    },
    "2" : {
      "cnnToFeedForward" : {
        "inputWidth" : 28,
        "inputHeight" : 28,
        "numChannels" : 1
      }
    }
```

Closes #565.

### CODE REVIEW

File: deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/preprocessor/UnitVarianceProcessor.java [hunk 1]
```diff
@@ -28,8 +32,11 @@
  *
  * @author Adma Gibson
  */
+@Data
 public class UnitVarianceProcessor extends BaseInputPreProcessor {
 
+    @Getter(AccessLevel.NONE)
+    @Setter(AccessLevel.NONE)
```
Comment (EronWright) [inline deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/preprocessor/UnitVarianceProcessor.java]: These annotations are needed to hide the columnStds field.   It is not really a part of the configuration, rather it looks to be internal state kept during execution.

File: deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/preprocessor/BaseInputPreProcessor.java [hunk 2]
```diff
@@ -7,10 +7,4 @@
  */
 
 public abstract class BaseInputPreProcessor implements InputPreProcessor {
-
-
-    @Override
-    public boolean equals(Object obj) {
-        return getClass().toString().equals(obj.getClass().toString());
-    }
```
Comment (EronWright) [inline deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/preprocessor/BaseInputPreProcessor.java]: This override seems evil; subtypes should provide a meaningful implementation.

**Comment by EronWright** [comment]
I tested this by running all unit tests that I could find related to input preprocessing:

- MultiLayerNeuralNetConfigurationTest
- ReshapePreProcessorTest
- CNNProcessorTest
