### PR TITLE
Fix standardize to avoid divide by zero

### LINKED ISSUE #9821: Infinite Value When using sd.nn.layerNorm Op
#### Issue Description
When using sd.nn.layerNorm op, I got the infinite value if all elements all equal and the number of elements is greater than 10 (<10 is correct). Pls help to check the code below:
  ```
public class TestLayerNormOp {
	  private SameDiff sd = null;
	  
	  @Before
	  public void init() {
		  sd = SameDiff.create();
	  }
	  
	  @Test
	  public void test() {
		  //seed
		  Nd4j.getRandom().setSeed(1234L);
		  //mock input tensor
		  int X = 2, Y = 3, Z = 10;
		  float[][][] arr = new float[X][Y][Z];
		  for( int i = 0; i < X; ++i ) {
			  for( int j = 0; j < Y; ++j ) {
				  for( int k = 0; k < Z; ++k ) {
					  arr[i][j][k] = 1.5678f;
				  }
			  }
		  }
		  //test layer norm op
		  int[] layerNormDimension = new int[] {2};
		  SDVariable input = sd.constant("input", Nd4j.createFromArray(arr));
		  SDVariable gain = sd.constant("gain", Nd4j.ones(DataType.FLOAT, Z));
		  SDVariable bias = sd.constant("bias", Nd4j.zeros(DataType.FLOAT, Z));
		  SDVariable output = sd.nn.layerNorm("output", input, gain, bias, false, layerNormDimension);
		  //print layer norm value
		  System.out.println(output.eval());
	  }
	  
	  @After
	  public void destroy() {
		  
	  }
  }
```
output1
====================================================================================
## **PS:  If I set the variable Z to 9, then got the correct result below**

output2

#### Version Information
* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Win10
* CUDA version, if used: **Not Used**
* NVIDIA driver version, if in use: **Not Used**

#### Additional Information

Where applicable, please also provide:
* pom.xml file or similar (also in a Gist): [pom.xml](https://gist.github.com/AllenWGX/0577bd01a0cded0e1faff3c57969b374)

### PR DESCRIPTION
**Pull request by agibsonccc**
Fix standardize to avoid divide by zero
Clean up commented old code present in standardize
Fixes #9821 
Fix codegen module layout

## What changes were proposed in this pull request?

Fix standardize to avoid divide by zero
Clean up commented old code present in standardize
## How was this patch tested?

Adds test that  triggers nan/inf validation to avoid the divide y zero
## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

File: libnd4j/include/ops/declarable/generic/transforms/standardize.cpp [hunk 1]
```diff
@@ -47,9 +47,9 @@ CONFIGURABLE_OP_IMPL(standardize, 1, 1, true, 0, -2) {
   shape::checkDimensions(input->rankOf(), axis);
 
   auto means = input->reduceAlongDimension(reduce::Mean, axis, true);
-  auto stdev = input->varianceAlongDimension(variance::SummaryStatsStandardDeviation, false, axis);
+  auto stdev = input->varianceAlongDimension(variance::SummaryStatsStandardDeviation, false, axis) + 1e-12;
   stdev.reshapei(means.getShapeAsVector());
-
+  stdev.printBuffer("Standard deviation\n");
```
Comment (treo) [inline libnd4j/include/ops/declarable/generic/transforms/standardize.cpp]: I guess this shouldn't be here.

**Review by treo — CHANGES_REQUESTED** [review]

File: libnd4j/include/ops/declarable/generic/transforms/standardize.cpp (hunk 1 above)
Comment (agibsonccc) [reply libnd4j/include/ops/declarable/generic/transforms/standardize.cpp]: @treo Thanks fixed!

**Review by treo — APPROVED** [review]
