### PR TITLE
Samediff training fixes 

### LINKED ISSUE #9862: SameDiff training broken in latest snapshot
#### Issue Description

In the latest snapshot, there seems to be a regression: Many computation graphs cannot be trained anymore, because of an `IllegalStateException`, which claims that the `graph does not contain any trainable SDVariables that the loss function depend on` (full stack trace below). Here's an example to reproduce:

```
int batchSize = 4;
int modelDim = 8;

SameDiff sd = SameDiff.create();

SDVariable features = sd.placeHolder("features", FLOAT, batchSize, modelDim);
SDVariable labels = sd.placeHolder("labels", FLOAT, batchSize, modelDim);
SDVariable weights = sd.var("weights", new XavierInitScheme('c', modelDim, modelDim), FLOAT, modelDim, modelDim);
SDVariable bias = sd.var("bias", new ZeroInitScheme('c'), FLOAT, modelDim);
SDVariable predictions = sd.nn.linear("predictions", features, weights, bias);
sd.loss.meanSquaredError("loss", labels, predictions, null);

TrainingConfig config = new TrainingConfig.Builder()
        .updater(new Adam(0.1))
        .dataSetFeatureMapping("features")
        .dataSetLabelMapping("labels")
        .build();
sd.setTrainingConfig(config);

DataSetIterator iterator = new RandomDataSetIterator(1, new long[]{batchSize, modelDim}, new long[]{batchSize, modelDim}, INTEGER_0_10, INTEGER_0_10);

sd.fit(iterator, 10);
```

#### Version Information

* Deeplearning4j version: 1.0.0-SNAPSHOT
* Platform information (OS, etc): Linux Mint 21
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

#### Additional Information

* Exception stack trace:
```
Exception in thread "main" java.lang.IllegalStateException: Cannot differentiate graph relative to the specified loss function variables [loss]: graph does not contain any trainable SDVariables (floating point VARIABLE type SDVariables) that the loss function depend on.
	at org.nd4j.common.base.Preconditions.throwStateEx(Preconditions.java:639)
	at org.nd4j.common.base.Preconditions.checkState(Preconditions.java:301)
	at org.nd4j.autodiff.samediff.SameDiff.lambda$createGradFunction$13(SameDiff.java:5152)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4733)
	at org.nd4j.autodiff.samediff.SameDiff.defineFunction(SameDiff.java:4718)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4938)
	at org.nd4j.autodiff.samediff.SameDiff.createGradFunction(SameDiff.java:4845)
	at org.nd4j.autodiff.samediff.SameDiff.fitHelper(SameDiff.java:1884)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1806)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1746)
	at org.nd4j.autodiff.samediff.config.FitConfig.exec(FitConfig.java:172)
	at org.nd4j.autodiff.samediff.SameDiff.fit(SameDiff.java:1726)
	at Backprop.main(Backprop.java:37)
```

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Fixes #9862
Fix training updates
Fix loss curve
Added new samediff test, reran older ones
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SameDiff.java [hunk 1]
```diff
@@ -4934,445 +4921,440 @@ Note that the user can also specify variables that they need gradients for (like
...
+        if (log.isTraceEnabled()) {
+            String[] initialOutputsStr = allFunctions.get(allFunctions.size() - 1).getOp().outputVariablesNames();
+            String s = initialOutputsStr == null ? "null" : Arrays.toString(initialOutputsStr);
+            log.trace("Defining backward function: initial outputs {}", s);
+        }
+
+
+        //----- Step 1: Determine FP variables connected to loss -----
+        // Find all FP variables that are connected to loss by a floating point (FP16/32/64) path
+        // Find all FP variables that are connected to loss by a floating point (FP16/32/64) path
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/samediff/SameDiff.java:4997]: Duplicated line.

**Review by treo — APPROVED** [review]
