### PR TITLE
Fixes https://github.com/eclipse/deeplearning4j/issues/9694

### LINKED ISSUE #9694: BooleanIndexing.replaceWhere Not Working Based On DataType
#### Issue Description
```
INDArray test =
        Nd4j.create(new double[] {1.0, 1.0, 2.0, 1.0}, new long[] {2, 2}, DataType.UINT16);
BooleanIndexing.replaceWhere(test, 0.0, Conditions.greaterThan(0)); // test not updated

INDArray testCasted = test.castTo(DataType.FLOAT);
BooleanIndexing.replaceWhere(testCasted, 0.0, Conditions.greaterThan(0)); // testCasted is updated
```
In the code above, an array created with UINT16 datatype doesn't get updated by the replaceWhere function. But when the array is casted to a FLOAT, replaceWhere works as expected.

#### Version Information
* Deeplearning4j version : 1.0.0-M2
* Platform information (OS, etc): Mac OS 12.3.1, 3 GHz 6-Core Intel Core i5, OpenJDK 11

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Fixes https://github.com/eclipse/deeplearning4j/issues/9694 with extra args and int arguments.
Ensures  properly typed buffers are created when accessing the constant buffer for extra args creation.

Mainly impacts CompareAndSet for BooleanIndexing.

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [X ] Relevant tests for your changes are passing.

### CODE REVIEW

File: nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/bindings/Nd4jCpu.java [hunk 1]
```diff
@@ -478,6 +478,13 @@ public native void copyBufferFrom(@Const @ByRef DataBuffer other, @Cast("size_t"
 
   public native void setPrimaryBuffer(Pointer buffer, @Cast("size_t") long length);
   public native void setSpecialBuffer(Pointer buffer, @Cast("size_t") long length);
+// #ifndef __JAVACPP_HACK__
+// #endif
+
+  public native void showBufferLimited();
+  //for Debug purposes
+  public native void showCounters(@Cast("char*") String msg1, @Cast("char*") String msg2);
+  public native void showCounters(@Cast("char*") BytePointer msg1, @Cast("char*") BytePointer msg2);
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/bindings/Nd4jCpu.java:487]: Were these changes supposed to make it into this pull request?

Comment (agibsonccc) [reply nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/bindings/Nd4jCpu.java:487]: Yes these are part of Rauf's VEDA PR. Either way this class will just be regenerated anyways.

**Review by treo — APPROVED** [review]
