### PR TITLE
Minor aurora fixes and rename

### LINKED ISSUE #9524: KerasModelImport: NullPointerException for top_level_model_weights layer
#### Issue Description

When I try to import my pre-trained keras tensorflow model, I encounter a NullPointerException.

```
String simpleMlp = new ClassPathResource("model.h5").getFile().getPath();
this.model = KerasModelImport.importKerasSequentialModelAndWeights(simpleMlp);
```

I am not sure if it is related to #8827

#### Version Information

* Deeplearning4j version 1.0.0-SNAPSHOT
* Platform information (OS, etc) Win-10

[pom.xml](https://gist.github.com/Foorcee/53ce4d7c200efb7e4944ee8e05e88e87)

#### Additional Information

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.deeplearning4j.nn.modelimport.keras.KerasLayer.getNumParams()" because the return value of "java.util.Map.get(Object)" is null
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.importWeights(KerasModelUtils.java:274)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:151)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:57)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:326)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:218)
```

https://github.com/eclipse/deeplearning4j/blob/master/deeplearning4j/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/utils/KerasModelUtils.java#L274

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Minor aurora rename import fixes.
Introduces a workaround to allow you to specify an absolute path to a compiled libnd4j binary
if not bundled.

Fixes https://github.com/eclipse/deeplearning4j/issues/9524
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ X] Created tests for any significant new code additions.
- [X ] Relevant tests for your changes are passing.

### CODE REVIEW

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java [hunk 1]
```diff
@@ -89,7 +89,7 @@ private NativeOpsHolder() {
                     .asSubclass(NativeOps.class);
             deviceNativeOps = ReflectionUtils.newInstance(nativeOpsClass);
 
-            deviceNativeOps.initializeDevicesAndFunctions();
+            //deviceNativeOps.initializeDevicesAndFunctions();
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java]: This looks weird. Why don't we want to initialize here? And if we really don't want that, maybe remove it entirely instead of commenting it out.

File: nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java [hunk 2]
```diff
@@ -55,7 +55,7 @@ public boolean allowsOrder() {
 
     @Override
     public int getPriority() {
-        return BACKEND_PRIORITY_CPU;
+        return BACKEND_PRIORITY_GPU;
```
Comment (treo) [inline nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java:58]: Maybe give it its own priority level?

**Review by treo — CHANGES_REQUESTED** [review]
Got a few more questions

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java (hunk 1 above)
Comment (agibsonccc) [reply nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java]: @treo ah yeah that was me testing a load_symbol problem and seeing what the source was. Uncommented now.

File: nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java (hunk 2 above)
Comment (agibsonccc) [reply nd4j/nd4j-backends/nd4j-backend-impls/nd4j-aurora/src/main/java/org/nd4j/linalg/aurora/AuroraBackend.java:58]: Done

File: nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java (hunk 1 above)
Comment (treo) [reply nd4j/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOpsHolder.java]: huh, as far as I can tell, this is still the same?

**Review by treo — DISMISSED** [review]

**Review by treo — APPROVED** [review]
