### PR TITLE
Bugfix 535 - remove redundant properties on NeuralNetConfiguration

### LINKED ISSUE #513: Configuration not set for certain global parameters
Some NN configuration parameters are not set if listed globally for the NN. Currently found for nIn and nOut. Following code leaves nIn and nOut as 0 in the Convolution configuration:

        NeuralNetConfiguration conf = new NeuralNetConfiguration.Builder()
                .layer(new ConvolutionLayer())
                .nIn(1)
                .nOut(2)
                .activationFunction("relu")
                .kernelSize(8, 8)
                .build();

In order to get the configuration to update with the new numbers, you have to use:

        NeuralNetConfiguration conf = new NeuralNetConfiguration.Builder()
                .activationFunction("relu")
                .layer(new ConvolutionLayer.Builder(new int[]{9, 9}, Convolution.Type.SAME).nIn(1).nOut(2).build())
                .build();

Note: If nIn and nOut is requried to be explicitly noted for each layer then hiddenLayerSizes is no longer needed and can be deprecated.
************
Update:

k is not being updated and only being set to 0 for contrastive divergence

### LINKED ISSUE #535: New layer API causes regression in old API (nIn, nOut erroneously set to zero)
- Rename `overRideField` to `overrideField` 
- Check integration of new API with the old

Certain neuralnetconfig properties seem to regress back to their default values. The problem is related to the new layer conf stuff. The overRideFields method sets the netconf’s property values to equal that of the layerconf’s values. But that makes sense only if you’re using the new API, otherwise the layerconf’s values are meaningless.

### LINKED ISSUE #567: NeuralNetConfigurationTest::testNeuralNetConfigAPI - convType mismatch
Stack trace:
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.deeplearning4j.nn.conf.NeuralNetConfLayerBuilderTest.testNeuralNetConfigAPI(NeuralNetConfLayerBuilderTest.java:96)
```

Line 96:
```
assertTrue(conv.conf().getConvolutionType().equals(newConvType));
```

A similar manifestation:
```
testLayerBuilderAPI(org.deeplearning4j.nn.layers.LayerBuilderTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.deeplearning4j.nn.layers.LayerBuilderTest.testLayerBuilderAPI(LayerBuilderTest.java:51)

```
Line 51:
```
assertTrue(conv.getConvolutionType() == convType);
```

### PR DESCRIPTION
**Pull request by EronWright**
- Removes obsolete conf properties that have moved to the layer API.  
- Fixes issues with certain properties on nnconf being ignored.
- Implements deep cloning of conf graph.

Closes #535.
Closes #567.
Closes #513.

### CODE REVIEW

**Comment by EronWright** [comment]
Outstanding work here:
- cleanup lossfunction
- cleanup all properties marked deprecated
- implement deep clone in nnconf.clone
- remove dead 'overridefields' method

**Comment by EronWright** [comment]
The entire configuration graph supports deep cloning now.   Previously the layers were not being copied.  This may solve a lot of subtle issues with the configuration dsl.

File: deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java [hunk 1]
```diff
@@ -68,13 +69,17 @@ public BaseLayer(NeuralNetConfiguration conf, INDArray input) {
         this.conf = conf;
     }
 
+    protected LayerConfT layerConf() {
```
Comment (EronWright) [inline deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java]: Here's the new way for layer execution code to obtain its corresponding layer configuration in a typed manner.

File: deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java [hunk 2]
```diff
@@ -534,18 +526,25 @@ public String toString() {
...
         INDArray b = getParam(DefaultParamInitializer.BIAS_KEY);
-        Layer layer = null;
+        Layer layer;
         try {
             Constructor c = getClass().getConstructor(NeuralNetConfiguration.class, INDArray.class, INDArray.class, INDArray.class);
-            NeuralNetConfiguration clone = conf.clone();
-            int nIn = clone.getNOut(),nOut = clone.getNIn();
-            clone.setNIn(nIn);
-            clone.setNOut(nOut);
+            NeuralNetConfiguration clone = conf.clone();  // assume a deep clone here
```
Comment (EronWright) [inline deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseLayer.java]: This is the line that precipitated a move to deep cloning, since the nIn/nOut are now buried inside the layer instance.

File: deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BasePretrainNetwork.java [hunk 3]
```diff
@@ -82,4 +85,21 @@ protected Gradient createGradient(INDArray wGradient,INDArray vBiasGradient,INDA
      */
     public abstract Pair<INDArray,INDArray> sampleVisibleGivenHidden(INDArray h);
 
+    @Override
+    protected void setScoreWithZ(INDArray z) {
```
Comment (EronWright) [inline deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BasePretrainNetwork.java]: Moved from BaseLayer.
